#!/bin/sh
# File generated by ocamlbuild

cd /Users/Anusha/Documents/ANUSHA/HARVARD/2023_SPRING/CS51/PSETS/PSET3

rm -f rsa_puzzle.ml.depends
# Also clean the script itself
rm -f /Users/Anusha/Documents/ANUSHA/HARVARD/2023_SPRING/CS51/PSETS/PSET3/_build/sanitize.sh
