#!/bin/sh
# File generated by ocamlbuild

cd /Users/Anusha/Documents/ANUSHA/HARVARD/2023_SPRING/CS51/PSETS/PSET6

rm -f Puzzle-Solver-master/collections.cmi
rm -f Puzzle-Solver-master/collections.cmo
rm -f Puzzle-Solver-master/puzzledescription.cmi
rm -f Puzzle-Solver-master/puzzledescription.cmo
rm -f Puzzle-Solver-master/puzzlesolve.cmi
rm -f Puzzle-Solver-master/puzzlesolve.cmo
rm -f TEST/collections.cmi
rm -f TEST/collections.cmo
rm -f collections.cmi
rm -f collections.cmo
rm -f mazes.cmi
rm -f mazes.cmo
rm -f p.cmi
rm -f p.cmo
rm -f puzzledescription.cmi
rm -f puzzledescription.cmo
rm -f tiles.cmi
rm -f tiles.cmo
# Also clean the script itself
rm -f /Users/Anusha/Documents/ANUSHA/HARVARD/2023_SPRING/CS51/PSETS/PSET6/_build/sanitize.sh
