#!/bin/sh
# File generated by ocamlbuild

cd /Users/Anusha/Documents/ANUSHA/HARVARD/2023_SPRING/CS51/PSETS/PSET8

rm -f absbook.cmi
rm -f absbook.cmo
rm -f config.cmi
rm -f config.cmo
rm -f counter.cmi
rm -f counter.cmo
rm -f utilities.cmi
rm -f utilities.cmo
# Also clean the script itself
rm -f /Users/Anusha/Documents/ANUSHA/HARVARD/2023_SPRING/CS51/PSETS/PSET8/_build/sanitize.sh
